export const darkTheme = {
  // primary: "#121214",
  // // primary: "#121214",
  // secondary: "red",
  // // secondary: "#202024",
  // tertiary: "blue",
  // // tertiary: "#29292e",
  // quaternary: "pink",
  // // quaternary: "#323238",
  // quinary: "#red",
  // // quinary: "#7c7c8a",
  // sextenario: "green",
  // // sextenario: "#8d8d99",
  // sectuenario: "orange",
  // // sectuenario: "#c4c4cc",
  primary: "#121212",
  secondary: "#1E1E1E",
  tertiary: "#2E2E2E",
  quaternary: "#3E3E3E",
  quinary: "#CCCCCC",
  sextenary: "#FFFFFF",
  septenary: "#F2F2F2",
};
