export const darkTheme = {
  primary: "#121214",
  // primary: "#121214",
  secondary: "red",
  // secondary: "#202024",
  tertiary: "blue",
  // tertiary: "#29292e",
  quaternary: "pink",
  // quaternary: "#323238",
  quinary: "#red",
  // quinary: "#7c7c8a",
  sextenario: "green",
  // sextenario: "#8d8d99",
  sectuenario: "orange",
  // sectuenario: "#c4c4cc",
};
